### ISSUE TITLE
npm run start，页面报错！

### ISSUE THREAD

**Issue by wwb568109135** [oliyg/hapiblog#2]
npm run start

![image](https://user-images.githubusercontent.com/5113679/47280828-cf419980-d60a-11e8-9cfa-fe3c91be099f.png)

===========================

sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
/Users/jerry/demo/hapiblog/node_modules/hoek/lib/index.js:740
    throw new Error(msgs.join(' ') || 'Unknown error');
    ^

Error: Invalid connection options {
  "compression": true,
  "router": {
    "isCaseSensitive": true,
    "stripTrailingSlash": false
  },
  "routes": {
    "cache": {
      "statuses": [
        200,
        204
      ],
      "otherwise": "no-cache"
    },
    "compression": {},
    "cors": false,
    "files": {
      "relativeTo": "."
    },
    "json": {
      "replacer": null,
      "space": null,
      "suffix": null,
      "escape": false
    },
    "log": false,
    "payload": {
      "failAction": "error",
      "maxBytes": 1048576,
      "output": "data",
      "parse": true,
      "timeout": 10000,
      "uploads": "/var/folders/3n/15_qj3ts07b4wm928grxy3700000gn/T",
      "defaultContentType": "application/json",
      "compression": {}
    },
    "response": {
      "ranges": true,
      "emptyStatusCode": 200,
      "options": {}
    },
    "security": null,
    "state": {
      "parse": true,
      "failAction": "error"
    },
    "timeout": {
      "server": false
    },
    "validate": {
      "options": {}
    }
  },
  "host": "HOST",
  "port" [1, 2, 3]: "PORT"
}

[1] "port" must be a number
[2] "port" with value "PORT" fails to match the required pattern: /\//
[3] "port" with value "PORT" fails to match the required pattern: /^\\\\\.\\pipe\\/
    at Object.exports.assert (/Users/jerry/demo/hapiblog/node_modules/hoek/lib/index.js:740:11)
    at Object.exports.apply (/Users/jerry/demo/hapiblog/node_modules/hapi/lib/schema.js:17:10)
    at concat.forEach (/Users/jerry/demo/hapiblog/node_modules/hapi/lib/server.js:165:27)
    at Array.forEach (<anonymous>)
    at module.exports.internals.Server.internals.Server.connection (/Users/jerry/demo/hapiblog/node_modules/hapi/lib/server.js:159:24)
    at Object.<anonymous> (/Users/jerry/demo/hapiblog/app.js:18:8)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
[nodemon] app crashed - waiting for file changes before starting...

**Comment by wwb568109135** [comment]
多提了
